# System Validator / Theaterverse Final
# Default application configuration values

SYSTEM_VALIDATOR_ENV: development
SYSTEM_VALIDATOR_BASE_DIR: /root/System_Validator/APP_DIR/theaterverse_final
API_BIND_HOST: 0.0.0.0
API_BIND_PORT: 8080
UI_DIST_DIR: /root/System_Validator/APP_DIR/theaterverse_final/ui/dist
LOG_LEVEL: INFO
BLUEGREEN_SLOT: A

# Database
SYSTEM_VALIDATOR_DSN: postgresql://validator:validator@localhost:5432/validator

# Observability
METRICS_PORT: 9000

# Security / RBAC
DEFAULT_ROLE: viewer

--- END OF STRUCTURE ---
# /root/System_Validator/APP_DIR/theaterverse_final/config/config_app_defaults.yaml
# /root/System_Validator/APP_DIR/theaterverse_final/config/config_app_defaults.yaml
# --- END OF STRUCTURE ---
